name: build-windows

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 关键修改：用 npm install 替代 npm ci，避免因 lock 文件不同步而失败
      - name: Install dependencies
        run: npm install

      - name: Build Electron app (Win)
        run: npm run build:win

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-windows
          path: |
            dist/*.exe
            dist/*.msi
            dist/*.zip
          if-no-files-found: error
