name: Build Windows Installer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create dist directory
      run: mkdir -p dist
      shell: bash
    
    - name: Build Windows executable
      run: npm run build:win
    
    - name: Verify executable was created
      run: |
        if (Test-Path "dist/PSBatchRunner.exe") {
          Write-Host "✓ PSBatchRunner.exe created successfully"
          Get-Item "dist/PSBatchRunner.exe" | Select-Object Name, Length, LastWriteTime
        } else {
          Write-Error "❌ PSBatchRunner.exe was not created"
          exit 1
        }
      shell: powershell
    
    - name: Setup Inno Setup
      run: |
        Write-Host "Installing Inno Setup..."
        choco install innosetup -y --no-progress
        Write-Host "Inno Setup installation completed"
      shell: powershell
    
    - name: Verify Inno Setup installation
      run: |
        $innoPath = "C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
        if (Test-Path $innoPath) {
          Write-Host "✓ Inno Setup found at: $innoPath"
          & $innoPath /? | Select-Object -First 3
        } else {
          Write-Error "❌ Inno Setup not found at expected path: $innoPath"
          Get-ChildItem "C:\Program Files (x86)" -Filter "*Inno*" -Directory -ErrorAction SilentlyContinue
          exit 1
        }
      shell: powershell
    
    - name: Build installer
      run: |
        $innoPath = "C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
        $scriptPath = "installer.iss"
        
        Write-Host "Building installer with Inno Setup..."
        Write-Host "Script path: $scriptPath"
        Write-Host "Inno Setup path: $innoPath"
        
        if (Test-Path $scriptPath) {
          Write-Host "✓ Installer script found"
        } else {
          Write-Error "❌ Installer script not found: $scriptPath"
          exit 1
        }
        
        & $innoPath $scriptPath
        
        if ($LASTEXITCODE -eq 0) {
          Write-Host "✓ Installer built successfully"
        } else {
          Write-Error "❌ Installer build failed with exit code: $LASTEXITCODE"
          exit 1
        }
      shell: powershell
    
    - name: Verify installer was created
      run: |
        if (Test-Path "dist/PSBatchRunner-Setup.exe") {
          Write-Host "✓ Installer created successfully"
          Get-Item "dist/PSBatchRunner-Setup.exe" | Select-Object Name, Length, LastWriteTime
        } else {
          Write-Error "❌ Installer was not created"
          Get-ChildItem "dist" -ErrorAction SilentlyContinue
          exit 1
        }
      shell: powershell
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-installer
        path: |
          dist/PSBatchRunner.exe
          dist/PSBatchRunner-Setup.exe
        retention-days: 30